apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-demo

spec:
  replicas: 4
  selector: 
    env: production
  template:
    metadata:
      name: pod-rc
      labels:
        env: production
    spec:
      containers:
        -  name: web-server
           image: "httpd"
